concurrency:
  cancel-in-progress: true
  group: ci-cd-${{ github.workflow }}-${{ github.ref }}
jobs:
  snapshot:
    name: Deploy snapshots
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Install just
      uses: taiki-e/install-action@just
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SECRET_FILES_PASSPHRASE: ${{ secrets.SECRET_FILES_PASSPHRASE }}
      name: Test and deploy snapshots
      run: "VERSION=$(./mvnw -q exec:exec -Dexec.executable=echo -Dexec.args='${project.version}'\
        \ -pl :mutiny-project)\nif [[ ${VERSION} == *SNAPSHOT ]]; then\n    echo \"\
        \U0001F680 Run the tests\"\n    ./mvnw --no-transfer-progress -s .build/maven-ci-settings.xml\
        \ -B clean verify\n    echo \"\U0001F680 Deploy the snapshots\"\n    just\
        \ -f .build/justfile-for-release -d . deploy-to-maven-central \nelse\n   \
        \ echo \"\U0001F90C This is a release commit, we won't do anything!\"\nfi\n"
name: Main branch continuous integration and snapshots deployment
on:
  repository_dispatch:
    types: trigger-ga___build-main.yml
