concurrency:
  cancel-in-progress: true
  group: check-pull-request-1.x-${{ github.workflow }}-${{ github.ref }}
jobs:
  build:
    name: Build with Java 8
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: set up jdk 8
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      env:
        MAVEN_OPTS: ${{ matrix.java.opts }}
      name: Build with Maven
      run: ./mvnw --no-transfer-progress -s .build/maven-ci-settings.xml -B clean
        verify
    - continue-on-error: true
      name: Compatibility Check
      run: ./mvnw --no-transfer-progress -s .build/maven-ci-settings.xml -pl '!bom'
        -B install revapi:check@check-compatibility -DskipTests -fae
name: Check pull requests (1.x branch)
on:
  repository_dispatch:
    types: trigger-ga___build-pull-1.x.yml
