jobs:
  deploy-web-site:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.ref }}
        token: ${{ secrets.RELEASE_TOKEN }}
    - continue-on-error: true
      name: Setup yq (portable yaml processor)
      uses: mikefarah/yq@master
    - continue-on-error: true
      name: Install just
      uses: taiki-e/install-action@just
    - continue-on-error: true
      name: Setup Git
      run: just -f .build/justfile-for-release -d . init-git
    - continue-on-error: true
      name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - continue-on-error: true
      name: Install MkDocs dependencies
      run: .build/install-mkdocs-deps.sh
    - continue-on-error: true
      name: Deploy the website
      run: .build/deploy-site.sh
name: Manual website deployment
on:
  repository_dispatch:
    types: trigger-ga___deploy-site.yml
