jobs:
  release:
    env:
      SECRET_FILES_PASSPHRASE: ${{ secrets.SECRET_FILES_PASSPHRASE }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Git checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Java setup
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Install just
      uses: taiki-e/install-action@just
    - continue-on-error: true
      name: Deploy to Maven Central
      run: just -f .build/justfile-for-release -d . deploy-to-maven-central
name: Push a release to Maven Central
on:
  repository_dispatch:
    types: trigger-ga___push-release-to-maven-central.yml
